pipeline {
    agent {
        docker { image 'zenika/alpine-chrome:with-node' }
    }
    options {
        buildDiscarder logRotator(daysToKeepStr: '5', numToKeepStr: '5')
    }
    stages {
        stage('check npm version') {
            steps {
                sh 'npm -v'
            }
        }
        stage('Git pull') {
          steps {
            git branch: 'main', url: 'https://github.com/EmmyHermans/Jenkins-SIG'
          }
        }
        stage('Install frontend dependencies') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm ci'
                echo "installed frontend end"
            }
        }
        stage('Test frontend') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm run test:ci'
                echo "Tested frontend end"
            }
        }
        stage('Build frontend') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm run build'
                echo "build frontend"
                sh 'cd koa-angular-app/koa-backend/src && mkdir public'
                sh 'cd koa-angular-app && mv -f ./angular-frontend/dist/angular-frontend ./koa-backend/src/public'
            }
        }
        stage('Install backend dependencies') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm ci'
                    echo "installed backend end"
                }
            }
        }
        stage('Test backend') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm test'
                    echo "Tested backend end"
                }
            }
        }
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
    }
}