pipeline {
    agent {
        docker { 
            image 'zenika/alpine-chrome:with-node'
            args '-p 3100:3100' 
        }
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '5'))
    }
    triggers { 
        pollSCM('* * * * *') 
    }
    stages {
        stage('check npm version') {
            steps {
                sh 'npm -v'
            }
        }
        stage('Git pull') {
          steps {
            git branch: 'any', url: 'https://github.com/EmmyHermans/Jenkins-SIG'
          }
        }
        stage('Install frontend dependencies') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm ci'
                echo "installed frontend end"
            }
        }
        stage('Test frontend') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm run test:ci'
                echo "Tested frontend end"
            }
        }
        stage('Install backend dependencies') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm ci'
                    echo "installed backend end"
                }
            }
        }
        stage('Test backend') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm test'
                    echo "Tested backend end"
                }
            }
        }
        stage('Build') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm run build'
                echo "build frontend"
                sh 'cd koa-angular-app/koa-backend/src && mkdir -p public'
                sh "cd koa-angular-app && rm -rf ./koa-backend/src/public"
                sh 'cd koa-angular-app && mv -f ./angular-frontend/dist/angular-frontend ./koa-backend/src/public'
            }
        }
        stage('Deliver') {
            steps {
                sh '''set -x
                cd koa-angular-app/koa-backend && npm run prod &
                sleep 1
                echo $! > koa-angular-app/koa-backend/.pidfile
                set +x
                echo \'Bezoek http://localhost:3100 om je Angular app te zien!\''''
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(cat koa-angular-app/koa-backend/.pidfile)'
            }
        }
        stage('Only for develop') {
            when {
                branch 'develop'
            }
            steps {
                echo "ONLY FOR DEVELOP!!"
            }
        }
    }
    post {
        always {
            echo 'Always clean the workspace'
            cleanWs() 
        }
        failure {
            echo 'I failed :('
        }
    }
}