pipeline {
    agent {
        docker { 
            image 'zenika/alpine-chrome:with-node'
            args '-p 3100:3100' 
        }
    }
    environment {
        FRONTEND_DIR = 'koa-angular-app/angular-frontend'
    }
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '5'))
    }
    triggers { 
        pollSCM('* * * * *') 
    }
    stages {
        stage('check npm version') {
            steps {
                sh 'npm -v'
            }
        }
        stage('Git pull') {
          steps {
            git branch: 'main', url: '/home/Code/SIGs/jenkins/Jenkins-SIG'
          }
        }
        stage('Install frontend dependencies') {
            steps {
                sh 'cd $FRONTEND_DIR && npm ci'
                echo "installed frontend end"
            }
        }
        stage('Test frontend') {
            steps {
                sh 'cd koa-angular-app/angular-frontend && npm run test:ci'
                echo "Tested frontend end"
            }
        }
        stage('Install backend dependencies') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm ci'
                    echo "installed backend end"
                }
            }
        }
        stage('Test backend') {
            steps {
                dir('koa-angular-app/koa-backend') {
                    sh 'npm test'
                    echo "Tested backend end"
                }
            }
        }
        stage('Build') {
            steps {
                dir('koa-angular-app') {
                    sh 'cd angular-frontend && npm run build'
                    echo "build frontend"
                    sh 'cd koa-backend/src && mkdir -p public'
                    sh "rm -rf ./koa-backend/src/public"
                    sh 'mv -f ./angular-frontend/dist/angular-frontend ./koa-backend/src/public'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '''set -x
                cd koa-angular-app/koa-backend && npm run prod &
                sleep 1
                echo $! > koa-angular-app/koa-backend/.pidfile
                set +x
                echo \'Bezoek http://localhost:3100 om je Angular app te zien!\''''
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(cat koa-angular-app/koa-backend/.pidfile)'
            }
        }
        stage('Only for 35th build') {
            when {
                environment name: 'BUILD_NUMBER', value: '35'
            }
            steps {
                echo "THIS IS BUILD 35!!!"
            }
        }
    }
    post {
        always {
            echo 'Always clean the workspace'
            cleanWs() 
        }
        failure {
            echo 'I failed :('
        }
    }
}